name: Preprocesar Datos


on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecución manual
    
jobs:
  preprocesar-datos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Listar directorio actual y archivos
        run: |
          pwd
          ls -lah

      - name: Preprocesar Datos para Entrenamiento
        run: python ./codigo/routines/preprocesar_datos.py -y 2022 2026 -ow False
